/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayFruitRouteImport } from './routes/play.fruit'
import { Route as PlayDucksRouteImport } from './routes/play.ducks'
import { Route as PlayDeepdiveRouteImport } from './routes/play.deepdive'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFruitRoute = PlayFruitRouteImport.update({
  id: '/play/fruit',
  path: '/play/fruit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDucksRoute = PlayDucksRouteImport.update({
  id: '/play/ducks',
  path: '/play/ducks',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDeepdiveRoute = PlayDeepdiveRouteImport.update({
  id: '/play/deepdive',
  path: '/play/deepdive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/play/deepdive': typeof PlayDeepdiveRoute
  '/play/ducks': typeof PlayDucksRoute
  '/play/fruit': typeof PlayFruitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/play/deepdive': typeof PlayDeepdiveRoute
  '/play/ducks': typeof PlayDucksRoute
  '/play/fruit': typeof PlayFruitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/play/deepdive': typeof PlayDeepdiveRoute
  '/play/ducks': typeof PlayDucksRoute
  '/play/fruit': typeof PlayFruitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/stats'
    | '/play/deepdive'
    | '/play/ducks'
    | '/play/fruit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/stats'
    | '/play/deepdive'
    | '/play/ducks'
    | '/play/fruit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/stats'
    | '/play/deepdive'
    | '/play/ducks'
    | '/play/fruit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  StatsRoute: typeof StatsRoute
  PlayDeepdiveRoute: typeof PlayDeepdiveRoute
  PlayDucksRoute: typeof PlayDucksRoute
  PlayFruitRoute: typeof PlayFruitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/fruit': {
      id: '/play/fruit'
      path: '/play/fruit'
      fullPath: '/play/fruit'
      preLoaderRoute: typeof PlayFruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/ducks': {
      id: '/play/ducks'
      path: '/play/ducks'
      fullPath: '/play/ducks'
      preLoaderRoute: typeof PlayDucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/deepdive': {
      id: '/play/deepdive'
      path: '/play/deepdive'
      fullPath: '/play/deepdive'
      preLoaderRoute: typeof PlayDeepdiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  StatsRoute: StatsRoute,
  PlayDeepdiveRoute: PlayDeepdiveRoute,
  PlayDucksRoute: PlayDucksRoute,
  PlayFruitRoute: PlayFruitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
